services:
  - type: web
    name: hashmind-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: DEPLOYER_PRIVATE_KEY
        sync: false
      - key: CONTRACT_ADDRESS
        sync: false
      - key: HASHKEY_RPC
        value: https://mainnet.hsk.xyz
